/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CadEngineeringRouteImport } from './routes/cad-engineering'
import { Route as CadServicesRouteImport } from './routes/cad-services'
import { Route as ComputerServicesRouteImport } from './routes/computer-services'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DigitalServicesRouteImport } from './routes/digital-services'
import { Route as GamingRouteImport } from './routes/gaming'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as SoftwareRouteImport } from './routes/software'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CadEngineeringRoute = CadEngineeringRouteImport.update({
  id: '/cad-engineering',
  path: '/cad-engineering',
  getParentRoute: () => rootRouteImport,
} as any)
const CadServicesRoute = CadServicesRouteImport.update({
  id: '/cad-services',
  path: '/cad-services',
  getParentRoute: () => rootRouteImport,
} as any)
const ComputerServicesRoute = ComputerServicesRouteImport.update({
  id: '/computer-services',
  path: '/computer-services',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalServicesRoute = DigitalServicesRouteImport.update({
  id: '/digital-services',
  path: '/digital-services',
  getParentRoute: () => rootRouteImport,
} as any)
const GamingRoute = GamingRouteImport.update({
  id: '/gaming',
  path: '/gaming',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const SoftwareRoute = SoftwareRouteImport.update({
  id: '/software',
  path: '/software',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cad-engineering': typeof CadEngineeringRoute
  '/cad-services': typeof CadServicesRoute
  '/computer-services': typeof ComputerServicesRoute
  '/contact': typeof ContactRoute
  '/digital-services': typeof DigitalServicesRoute
  '/gaming': typeof GamingRoute
  '/pricing': typeof PricingRoute
  '/software': typeof SoftwareRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cad-engineering': typeof CadEngineeringRoute
  '/cad-services': typeof CadServicesRoute
  '/computer-services': typeof ComputerServicesRoute
  '/contact': typeof ContactRoute
  '/digital-services': typeof DigitalServicesRoute
  '/gaming': typeof GamingRoute
  '/pricing': typeof PricingRoute
  '/software': typeof SoftwareRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cad-engineering': typeof CadEngineeringRoute
  '/cad-services': typeof CadServicesRoute
  '/computer-services': typeof ComputerServicesRoute
  '/contact': typeof ContactRoute
  '/digital-services': typeof DigitalServicesRoute
  '/gaming': typeof GamingRoute
  '/pricing': typeof PricingRoute
  '/software': typeof SoftwareRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cad-engineering'
    | '/cad-services'
    | '/computer-services'
    | '/contact'
    | '/digital-services'
    | '/gaming'
    | '/pricing'
    | '/software'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cad-engineering'
    | '/cad-services'
    | '/computer-services'
    | '/contact'
    | '/digital-services'
    | '/gaming'
    | '/pricing'
    | '/software'
  id:
    | '__root__'
    | '/'
    | '/cad-engineering'
    | '/cad-services'
    | '/computer-services'
    | '/contact'
    | '/digital-services'
    | '/gaming'
    | '/pricing'
    | '/software'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadEngineeringRoute: typeof CadEngineeringRoute
  CadServicesRoute: typeof CadServicesRoute
  ComputerServicesRoute: typeof ComputerServicesRoute
  ContactRoute: typeof ContactRoute
  DigitalServicesRoute: typeof DigitalServicesRoute
  GamingRoute: typeof GamingRoute
  PricingRoute: typeof PricingRoute
  SoftwareRoute: typeof SoftwareRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cad-engineering': {
      id: '/cad-engineering'
      path: '/cad-engineering'
      fullPath: '/cad-engineering'
      preLoaderRoute: typeof CadEngineeringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cad-services': {
      id: '/cad-services'
      path: '/cad-services'
      fullPath: '/cad-services'
      preLoaderRoute: typeof CadServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/computer-services': {
      id: '/computer-services'
      path: '/computer-services'
      fullPath: '/computer-services'
      preLoaderRoute: typeof ComputerServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-services': {
      id: '/digital-services'
      path: '/digital-services'
      fullPath: '/digital-services'
      preLoaderRoute: typeof DigitalServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gaming': {
      id: '/gaming'
      path: '/gaming'
      fullPath: '/gaming'
      preLoaderRoute: typeof GamingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/software': {
      id: '/software'
      path: '/software'
      fullPath: '/software'
      preLoaderRoute: typeof SoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadEngineeringRoute: CadEngineeringRoute,
  CadServicesRoute: CadServicesRoute,
  ComputerServicesRoute: ComputerServicesRoute,
  ContactRoute: ContactRoute,
  DigitalServicesRoute: DigitalServicesRoute,
  GamingRoute: GamingRoute,
  PricingRoute: PricingRoute,
  SoftwareRoute: SoftwareRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
